version: '3.7'

services:

  gateway:
    image: guybiton7/gateway:0.0.1-SNAPSHOT
    ports: 
      - "9090:9090"
    networks:
      - gb-network
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka

  eureka-server:
    image: guybiton7/eureka-server:0.0.1-SNAPSHOT
    ports: 
      - "8761:8761"
    networks:
      - gb-network
          
networks:
  gb-network: